# fly.toml app configuration file generated for duration-prediction on 2025-01-10T11:00:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'duration-prediction'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 9696
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
